### PR TITLE
Adds a visually hidden component

### PR DESCRIPTION
**Pull request by zamith**

### CODE REVIEW

**Comment by gabrielpoca** [comment]
Can you add the sc5 comments for this component? What exactly is the purpose of it?

**Comment by zamith** [comment]
@gabrielpoca bump

**Comment by gabrielpoca** [comment]
In my perspective it would make more sense for this to be a modifier, but let's have @azevedo-252 opinion on this

**Comment by azevedo-252** [comment]
A modifier??
Did you mean a utility? If so, it does behave like a utility, even though it does more things than a typical one.
I'm ok with either one. Perhaps a utility makes more sense.

**Comment by gabrielpoca** [comment]
Ups, I meant utility.

**Comment by zamith** [comment]
We've had this discussion in the past and decided to go with a component.
But I'm fine with using an utility.

**Comment by zamith** [comment]
@gabrielpoca bump

**Comment by gabrielpoca** [comment]
:+1:

**Pull request merged**
