### PR TITLE
Adds pre-compiled files

### PR DESCRIPTION
**Pull request by naps62**

### CODE REVIEW

**Comment by zamith** [comment]
Should we have the minified versions as well?

**Comment by gabrielpoca** [comment]
can we use gulp instead? If we are writing the build system ourselves, I would rather gulp, I've built complex build systems on it and believe it's better.

**Comment by naps62** [comment]
@gabrielpoca fine by me, but you'll have to do that yourself (or someone else), since I haven't used gulp that much

But what the reasons? Are they strong enough to rebuild something that's already working?

**Comment by gabrielpoca** [comment]
@naps62 I already have a nice solution for this, I've built one for myself some time ago. My reasons are the same as everyone else. Gulp is easier to use, it's javascript and streams, grunt is a giant configuration file. And with gulp you can just use node modules. With grunt you need to wrap everything. Streams make it easier to read and understand. This is a personal preference, they have both the same potential.

**Comment by naps62** [comment]
@gabrielpoca fine by me. Can you make the changes on this branch then? I'l like to get this merged as soon as possible, since I'm using it in codepen

**Comment by gabrielpoca** [comment]
@naps62 done, what do you think?

**Pull request merged**
