### PR TITLE
Adds Media--responsive

### PR DESCRIPTION
**Pull request by naps62**
This is needed on the blog (and could be used to refactor other things on the rest of the apps as well

### CODE REVIEW

**Comment by azevedo-252** [comment]
Where is this needed?
This is not the definition of a media object, as defined by stubbornella. I feel that this shouldn't be here.

**Comment by gabrielpoca** [comment]
It would make sense for this object to adapt to the viewport. But you can allways consider this an edge case.

**Comment by azevedo-252** [comment]
Well if it needs to adapt to a column layout, then it shouldn't be a Media object. That's all I'm saying

**Comment by gabrielpoca** [comment]
I don't have a so stritc defenition, how "HorizontalGrid" also adapts to column. And it's called horizontal.

**Comment by azevedo-252** [comment]
That's just an unfortunate name, it should have a better name as everything :) Should not serve as example.

But ok, it's a modifier, and it's not like it is an absolute and undeniable truth.

**Comment by gabrielpoca** [comment]
For me it would make more sense to keep this in the blog until it's used somewhere else, but I'm ok eitherway.

**Comment by naps62** [comment]
It would be usable, for example, in the CS case study, where I'm currently using a HorizontalGrid. Although that has problems when the content is larger, which is why I need this one on the blog

I had no idea at all that this Media component was a "thing", defined by stubornella (maybe that should be in the component's docs?

Anyway, please reach an agreement, and I'll do whatever you feel best (either have this here, or doing something specific for the blog)

**Comment by azevedo-252** [comment]
Use the modifier in the blog only then

**Comment by naps62** [comment]
Fine. Closing this then

**Pull request closed without merging**
